### ISSUE TITLE
few classes are missing which are ending with _ check the attached screenshot.

### ISSUE THREAD

**Issue by jjkayani** [thiaguimcavalcanti/hacker-rank-restapi-with-spring-boot#1]
![image](https://user-images.githubusercontent.com/25216840/63617411-7233bd00-c5fa-11e9-9e2e-294dec978079.png)

**Comment by poojaacacia** [comment]
yes, facing the same issue

**Comment by thiaguimcavalcanti** [comment]
Thanks for this callout... It was fixed in the latest version...

Please, follow these instructions:
https://github.com/thiaguimcavalcanti/hacker-rank-restapi-with-spring-boot#how-to-compile-and-run-the-application-with-an-example-for-each-call

Any questions, please let me know! :)
